Update net/vnstat to version 2.0

diff --git a/net/vnstat/files/vnstat.in b/net/vnstat/files/vnstat.in
--- a/net/vnstat/files/vnstat.in
+++ b/net/vnstat/files/vnstat.in
@@ -1,6 +1,6 @@
 #!/bin/sh
 # Created by: Mark Felder <feld@FreeBSD.org>
-# $FreeBSD: head/net/vnstat/files/vnstat.in 385777 2015-05-08 13:24:35Z feld $
+# $FreeBSD: head/net/vnstat/files/vnstat.in 485333 2018-11-19 17:29:51Z feld $
 
 # PROVIDE: vnstat
 # REQUIRE: LOGIN
@@ -35,8 +35,8 @@ create_iface_database()
 {
 	local iface="$1"
 	local descr="$2"
-	su -m ${vnstat_user} -c "${user_cmd} --create --iface $iface" >/dev/null 2>&1 ||
-	  ! echo "$name: Failed to create database for the $descr interface $iface" || return 1
+	su -m ${vnstat_user} -c "${user_cmd} --add --iface $iface" >/dev/null 2>&1 ||
+	  ! echo "$name: Failed to add database for the $descr interface $iface" || return 1
 	echo "$name: Created the database for the $descr interface $iface"
 }
 
