Update www/caddy to version 2.6.1_4

diff --git a/www/caddy/files/caddy.in b/www/caddy/files/caddy.in
--- a/www/caddy/files/caddy.in
+++ b/www/caddy/files/caddy.in
@@ -8,6 +8,7 @@
 # /etc/rc.conf.local
 
 # Optional settings:
+# caddy_command (string):     Full path to the caddy binary
 # caddy_config (string):      Full path to caddy config file
 #                             (%%ETCDIR%%/Caddyfile)
 # caddy_adapter (string):     Config adapter type (caddyfile)
@@ -38,7 +39,8 @@ load_rc_config $name
 # Defaults
 : ${caddy_enable:=NO}
 : ${caddy_adapter:=caddyfile}
-: ${caddy_config:=%%ETCDIR%%/Caddyfile}
+: ${caddy_config:="%%ETCDIR%%/Caddyfile"}
+: ${caddy_command:="%%PREFIX%%/bin/${name}"}
 : ${caddy_directory:=/var/db/caddy}
 : ${caddy_extra_flags:=""}
 : ${caddy_logdir:="/var/log/${name}"}
@@ -51,59 +53,76 @@ load_rc_config $name
 : ${XDG_DATA_HOME:="${caddy_directory}/data"}
 export XDG_CONFIG_HOME XDG_DATA_HOME
 
-command="%%PREFIX%%/bin/${name}"
+command="${caddy_command}"
 caddy_flags="--config ${caddy_config} --adapter ${caddy_adapter}"
 pidfile="/var/run/${name}/${name}.pid"
 
-required_files="${caddy_config} ${command}"
+required_files="${caddy_config} ${caddy_command}"
 
 start_precmd="caddy_precmd"
 start_cmd="caddy_start"
-stop_cmd="caddy_stop"
+stop_precmd="caddy_prestop"
 
 # Extra Commands
 extra_commands="configtest reload"
-configtest_cmd="caddy_command validate ${caddy_flags}"
-reload_cmd="caddy_command reload ${caddy_flags}"
+configtest_cmd="caddy_execute validate ${caddy_flags}"
+reload_cmd="caddy_execute reload ${caddy_flags}"
 
-caddy_command()
+caddy_execute()
 {
-	/usr/bin/su -m "${caddy_user}" -c "${command} $*"
+    /usr/bin/su -m "${caddy_user}" -c "${caddy_command} $*"
 }
 
 caddy_precmd()
 {
-	# Create required directories and set permissions
-	/usr/bin/install -d -m 755 -o "${caddy_user}" -g "${caddy_group}" ${caddy_directory}
-	/usr/bin/install -d -m 700 -o "${caddy_user}" -g "${caddy_group}" ${caddy_directory}/config
-	/usr/bin/install -d -m 700 -o "${caddy_user}" -g "${caddy_group}" ${caddy_directory}/data
-	/usr/bin/install -d -m 755 -o "${caddy_user}" -g "${caddy_group}" ${caddy_logdir}
-	/usr/bin/install -d -m 700 -o "${caddy_user}" -g "${caddy_group}" /var/run/caddy
+    # Create required directories and set permissions
+    /usr/bin/install -d -m 755 -o "${caddy_user}" -g "${caddy_group}" ${caddy_directory}
+    /usr/bin/install -d -m 700 -o "${caddy_user}" -g "${caddy_group}" ${caddy_directory}/config
+    /usr/bin/install -d -m 700 -o "${caddy_user}" -g "${caddy_group}" ${caddy_directory}/data
+    /usr/bin/install -d -m 755 -o "${caddy_user}" -g "${caddy_group}" ${caddy_logdir}
+    /usr/bin/install -d -m 700 -o "${caddy_user}" -g "${caddy_group}" /var/run/caddy
+    if [ -e ${caddy_logfile} ]; then
+        /bin/chmod 644 ${caddy_logfile}
+        /usr/sbin/chown root:wheel ${caddy_logfile}
+    else
+        /usr/bin/install -m 644 -o root -g wheel /dev/null ${caddy_logfile}
+    fi
 }
 
 caddy_start()
 {
-	echo -n "Starting caddy... "
-	/usr/bin/su -m ${caddy_user} -c "${command} start ${caddy_flags} \
-		${caddy_extra_flags} --pidfile ${pidfile}" >> ${caddy_logfile} 2>&1
-	if [ $? -eq 0 ] && ps -ax -o pid | grep -q "$(cat ${pidfile})"; then
-		echo "done"
-		echo "Log: ${caddy_logfile}"
-	else
-		echo "Error: Caddy failed to start"
-		echo "Check the caddy log: ${caddy_logfile}"
-	fi
+    echo -n "Starting caddy... "
+    /usr/bin/su -m ${caddy_user} -c "${caddy_command} start ${caddy_flags} \
+        ${caddy_extra_flags} --pidfile ${pidfile}" >> ${caddy_logfile} 2>&1
+    if [ $? -eq 0 ] && ps -ax -o pid | grep -q "$(cat ${pidfile})"; then
+        echo "done"
+        echo "Log: ${caddy_logfile}"
+    else
+        echo "Error: Caddy failed to start"
+        echo "Check the caddy log: ${caddy_logfile}"
+    fi
 }
 
-caddy_stop()
+caddy_prestop()
 {
-	echo -n "Stopping caddy... "
-	if caddy_command stop; then
-		echo "done"
-	else
-		echo "Error: Unable to stop caddy"
-		echo "Check the caddy log: ${caddy_logfile}"
-	fi
+    local result
+
+    echo -n "Stopping caddy... "
+
+    result="$(caddy_execute stop 2>&1)"
+    if [ ${?} -eq 0 ]; then
+        echo "done"
+        exit 0
+    else
+        if echo "${result}" | grep -q "connection refused"; then
+            echo "admin interface unavailable; using pidfile"
+            return 0
+        else
+            echo "Error: Unable to stop caddy"
+            echo "Check the caddy log: ${caddy_logfile}"
+            return 1
+        fi
+    fi
 }
 
 run_rc_command "$1"
