Tweak www/firefox-i18n version 29.0

diff --git a/www/firefox-i18n/Makefile b/www/firefox-i18n/Makefile
--- a/www/firefox-i18n/Makefile
+++ b/www/firefox-i18n/Makefile
@@ -50,9 +50,10 @@ pre-everything::
 
 do-extract:
 	@${MKDIR} ${WRKSRC}
-	@for lang in ${FIREFOX_I18N_}; do \
-		if ! (${UNZIP_CMD} ${EXTRACT_BEFORE_ARGS} ${_DISTDIR}/$$lang.xpi -d ${WRKSRC}/langpack-$$lang@firefox.mozilla.org);\
+	for lang in ${FIREFOX_I18N_}; do \
+		if ! (${UNZIP_CMD} -qo ${_DISTDIR}/$$lang.xpi -d ${WRKSRC}/langpack-$$lang@firefox.mozilla.org);\
 		then \
+			echo "extraction $$lang failed"; \
 			exit 1; \
 		fi; \
 		cd ${WRKSRC}/langpack-$$lang@firefox.mozilla.org/; \
