Update sysutils/devcpu-data to version 1.13_1

diff --git a/sysutils/devcpu-data/files/microcode_update.in b/sysutils/devcpu-data/files/microcode_update.in
--- a/sysutils/devcpu-data/files/microcode_update.in
+++ b/sysutils/devcpu-data/files/microcode_update.in
@@ -1,11 +1,12 @@
 #!/bin/sh
 #
-# $FreeBSD: head/sysutils/devcpu-data/files/microcode_update.in 452203 2017-10-16 16:37:56Z riggs $
+# $FreeBSD: head/sysutils/devcpu-data/files/microcode_update.in 458664 2018-01-10 17:32:14Z sbruno $
 #
 
 # PROVIDE:	microcode_update
 # REQUIRE:	root mountcritlocal
 # KEYWORD:	nojail
+# BEFORE:	SERVERS
 
 #
 # Add the following line to /etc/rc.conf to enable flow-capture:
@@ -41,7 +42,7 @@ microcode_update_prepare()
 
 microcode_update_start()
 {
-	echo "Updating cpucodes..."
+	echo "Updating CPU Microcode..."
 	if [ "${microcode_cpus}" = "ALL" ]; then
 		ncpu=`/sbin/sysctl -n hw.ncpu`
 		cpus=`jot ${ncpu} 0`;
@@ -50,9 +51,19 @@ microcode_update_start()
 	fi
 	for i in ${cpus}; do
 		${CMT} -u ${microcode_update_flags} \
-		    -d "${microcode_update_datadir}" /dev/cpuctl${i} || \
-		    (echo "Failed." && exit 1)
+                    -d "${microcode_update_datadir}" /dev/cpuctl${i} 2>&1 | \
+                    logger -p daemon.notice -t microcode_update || \
+		    (echo "Microcode Update Failed." && exit 1)
 	done
+	if [ "${microcode_cpus}" = "ALL" ]; then
+		for i in ${cpus}; do
+			${CMT} -e /dev/cpuctl${i} >/dev/null 2>&1
+			if [ $? -ne 0 ]; then
+				echo "Re-evalutation of CPU flags Failed."
+				exit 1
+			fi
+		done
+	fi
 	echo "Done."
 }
 
