Update sysutils/devcpu-data to version 1.15_1

diff --git a/sysutils/devcpu-data/files/microcode_update.in b/sysutils/devcpu-data/files/microcode_update.in
--- a/sysutils/devcpu-data/files/microcode_update.in
+++ b/sysutils/devcpu-data/files/microcode_update.in
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# $FreeBSD: head/sysutils/devcpu-data/files/microcode_update.in 458664 2018-01-10 17:32:14Z sbruno $
+# $FreeBSD: head/sysutils/devcpu-data/files/microcode_update.in 459084 2018-01-15 17:05:37Z swills $
 #
 
 # PROVIDE:	microcode_update
@@ -56,13 +56,16 @@ microcode_update_start()
 		    (echo "Microcode Update Failed." && exit 1)
 	done
 	if [ "${microcode_cpus}" = "ALL" ]; then
-		for i in ${cpus}; do
-			${CMT} -e /dev/cpuctl${i} >/dev/null 2>&1
+                CPUCONTROL_UPDATED=$(cpucontrol -h 2>&1 | grep -q -- -e; echo $?)
+                if [ ${CPUCONTROL_UPDATED} -ne 0 ]; then
+                        echo "Please update your system in order to update CPU microcode."
+                else
+			${CMT} -e /dev/cpuctl0 >/dev/null 2>&1
 			if [ $? -ne 0 ]; then
-				echo "Re-evalutation of CPU flags Failed."
+				echo "Re-evalulation of CPU flags Failed."
 				exit 1
 			fi
-		done
+                fi
 	fi
 	echo "Done."
 }
